### ISSUE TITLE
Feature Request: Add links shortcuts

### ISSUE THREAD

**Issue by ghost** [vhanla/vscode-extensions-readme#1]
Hey @vhanla ! 😊👋🏼

Using your extension is way more faster to reach an extension knowing its name.
What about adding two buttons in the top right corner for opening its repository and its marketplace sites (if they are available) ?

Another thing you could add: [quickPick items](https://code.visualstudio.com/api/references/vscode-api#QuickPickItem) can render descriptions, so there you could add extension's display names.

**Comment by ghost** [comment]
I believe this can help you:
When markdown previews are open vscode set a context `markdownPreviewFocus`=true
So you can use it in when clauses, and more specifically, in the `menus/editor/title` manifest section (See [this](https://code.visualstudio.com/api/references/contribution-points#menu-example)).
In order to create the two buttons you can write a when clause like this:
``` JSON
 {
                    "when": "markdownPreviewFocus && extension-readme.editorHasMarketplace",
                    "command": "extension-readme.openInMarketplace",
                    "group": "navigation@1"
                },
```

`extension-readme.editorHasMarketplace` could be another context managed by your extension.
You can set and unset context using the `setContext` context (if you are still using `extension-workbench` try the snippet called `contextOn`)

There are three places where you can set your context:
- when user quickPick an extension (dho!)
- during `vscode.workspace.onDidChangeTextDocument`
- during `vscode.workspace.onDidCloseTextDocument`

dulcis in fundo : [optional]  could be handy having a button for the changelog too

**Comment by vhanla** [comment]
Thanks for your suggestions, I modified it with your request and also changed markdown preview with new API `markdown.api.render` a997f37ecfe2565420ae6449b632c7c491b9607a , but changelog still renders using old method.

**Comment by ghost** [comment]
Great !👏🏼👏🏼👏🏼

Nice ideas the `markdown.api.render` and the displayed info in "ext.name ext.vers ext.pub" format 
Given that the repo and the marketplace depend on the internet
for the changelog maybe you could launch the online version too:
```Typescript
vscode.commands.executeCommand('vscode.open', vscode.Uri.parse
            (`https://marketplace.visualstudio.com/items/${currentExt.publisher}.${currentExt.name}/changeLog`));
```

Now i think it's perfect 👍🏼

**Comment by vhanla** [comment]
I don't know, marketplace's changelog is just two clicks away (counting the click to visit the marketplace site) 
![imagen](https://user-images.githubusercontent.com/1015823/76476421-f6e7fc00-63cf-11ea-8bfb-591bc4a18733.png)
 
I'll see.

**Comment by ghost** [comment]
As the Repository link is 😂
But i like buttons, more practical.
Maybe the best could be convert the old command to `markdown.api.render` too as the changelog.md resides on the extension folder too.
Local resources should be used as much as possible, instead of wasting precious bandwidth.
Thanks.

Just a matter of style:
Could you add this section to the package.json ?
``` JSON
"menus": {
    "commandPalette": [
        {
            "command": "extension.openRepository",
            "when": "never"
        },
        {
            "command": "extension.openChangelog",
            "when": "never"
        },
        {
            "command": "extension.openMarketplace",
            "when": "never"
        },
        {
            "command": "extension.openReadme",
            "when": "never"
        }
    ]
}
```
This would improve the UX, because those commands clutter the Command Palette without doing anything on they own.

For me the issue is closed, feel free to close it whenever you want.👍🏼
Thank you

**Comment by vhanla** [comment]
Glad you mentioned it, but as a keyboard user (more than mouse), I rather keep it, it comes handy to open its repository without leaving the keyboard. I think others would like to use it too.

**Comment by ghost** [comment]
P.S.
What about setting the scope of commands on the palette in the same way as buttons ?
``` JSON
"menus": {
    "commandPalette": [
        {
            "command": "extension.openRepository",
            "when": "(!readmeMarkdownFocused &&(markdownPreviewFocus || resourceLangId == markdown)) || readmeMarkdownFocused"
        },
        {
            "command": "extension.openChangelog",
            "when": "(!readmeMarkdownFocused &&(markdownPreviewFocus || resourceLangId == markdown)) || readmeMarkdownFocused"
        },
        {
            "command": "extension.openMarketplace",
            "when": "(!readmeMarkdownFocused &&(markdownPreviewFocus || resourceLangId == markdown)) || readmeMarkdownFocused"
        },
        {
            "command": "extension.openReadme",
            "when": "readmeMarkdownFocused"
        }
    ]
}
```
This will definitely benefit both kind of users 👍🏼

Yesterday i've discovered that you can call the command `markdown.showPreviewToSide` passing a file uri to open directly its preview without having to open its source file first.
Maybe this could simplify things:
``` Typescript
await vscode.commands.executeCommand('markdown.showPreview',vscode.Uri.file('path/to/changelog.md')));
```
Best !
